In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("pittsburgh2013.csv")

In [3]:
data.head(10)

,Date,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,Mean Dew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2013-1-1,32,28,21,30,27,16,100,89,77,...,10,6,2,10,8,NaN,0.00,8,Snow,277
1,2013-1-2,25,21,17,14,12,10,77,67,55,...,10,10,10,14,5,NaN,0.00,4,NaN,272
2,2013-1-3,32,24,16,19,15,9,77,67,56,...,10,10,10,17,8,26.0,0.00,3,NaN,229
3,2013-1-4,30,28,27,21,19,17,75,68,59,...,10,10,6,23,16,32.0,0.00,4,NaN,250
4,2013-1-5,34,30,25,23,20,16,75,68,61,...,10,10,10,16,10,23.0,0.21,5,NaN,221
5,2013-1-6,37,34,32,31,28,23,87,75,65,...,10,10,8,14,9,22.0,0.26,8,Snow,232
6,2013-1-7,33,29,25,27,24,21,86,78,65,...,10,7,4,10,8,NaN,0.06,5,NaN,236
7,2013-1-8,43,31,19,29,24,19,100,75,51,...,10,8,2,12,7,NaN,0.00,0,NaN,178
8,2013-1-9,45,36,28,39,32,25,89,76,65,...,10,10,5,18,11,25.0,0.03,3,Rain,211
9,2013-1-10,41,34,30,29,27,25,85,69,53,...,10,10,8,10,6,NaN,0.00,0,NaN,72

In [4]:
data.columns

Index(['Date', 'Max TemperatureF', 'Mean TemperatureF', 'Min TemperatureF',
       'Max Dew PointF', 'Mean Dew PointF', 'Min DewpointF', 'Max Humidity',
       'Mean Humidity', 'Min Humidity', 'Max Sea Level PressureIn',
       'Mean Sea Level PressureIn', 'Min Sea Level PressureIn',
       'Max VisibilityMiles', 'Mean VisibilityMiles', 'Min VisibilityMiles',
       'Max Wind SpeedMPH', 'Mean Wind SpeedMPH', 'Max Gust SpeedMPH',
       'PrecipitationIn', ' CloudCover', 'Events', 'WindDirDegrees'],
      dtype='object')

In [7]:
def to_celsius(F):
    return int(5/9*(F - 32))
data['Max TemperatureC']=data['Max TemperatureF'].apply(to_celsius)

In [8]:
data.head(10)

,Date,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,Mean Dew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,Max TemperatureC
0,2013-1-1,32,28,21,30,27,16,100,89,77,...,6,2,10,8,NaN,0.00,8,Snow,277,0
1,2013-1-2,25,21,17,14,12,10,77,67,55,...,10,10,14,5,NaN,0.00,4,NaN,272,-3
2,2013-1-3,32,24,16,19,15,9,77,67,56,...,10,10,17,8,26.0,0.00,3,NaN,229,0
3,2013-1-4,30,28,27,21,19,17,75,68,59,...,10,6,23,16,32.0,0.00,4,NaN,250,-1
4,2013-1-5,34,30,25,23,20,16,75,68,61,...,10,10,16,10,23.0,0.21,5,NaN,221,1
5,2013-1-6,37,34,32,31,28,23,87,75,65,...,10,8,14,9,22.0,0.26,8,Snow,232,2
6,2013-1-7,33,29,25,27,24,21,86,78,65,...,7,4,10,8,NaN,0.06,5,NaN,236,0
7,2013-1-8,43,31,19,29,24,19,100,75,51,...,8,2,12,7,NaN,0.00,0,NaN,178,6
8,2013-1-9,45,36,28,39,32,25,89,76,65,...,10,5,18,11,25.0,0.03,3,Rain,211,7
9,2013-1-10,41,34,30,29,27,25,85,69,53,...,10,8,10,6,NaN,0.00,0,NaN,72,5

In [9]:
dictw={'Rain': "10101" ,'Snow': "01010"}
data["dictw"]=data["Events"].map(dictw)

In [10]:
data.head(10)

,Date,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,Mean Dew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,Max TemperatureC,dictw
0,2013-1-1,32,28,21,30,27,16,100,89,77,...,2,10,8,NaN,0.00,8,Snow,277,0,01010
1,2013-1-2,25,21,17,14,12,10,77,67,55,...,10,14,5,NaN,0.00,4,NaN,272,-3,NaN
2,2013-1-3,32,24,16,19,15,9,77,67,56,...,10,17,8,26.0,0.00,3,NaN,229,0,NaN
3,2013-1-4,30,28,27,21,19,17,75,68,59,...,6,23,16,32.0,0.00,4,NaN,250,-1,NaN
4,2013-1-5,34,30,25,23,20,16,75,68,61,...,10,16,10,23.0,0.21,5,NaN,221,1,NaN
5,2013-1-6,37,34,32,31,28,23,87,75,65,...,8,14,9,22.0,0.26,8,Snow,232,2,01010
6,2013-1-7,33,29,25,27,24,21,86,78,65,...,4,10,8,NaN,0.06,5,NaN,236,0,NaN
7,2013-1-8,43,31,19,29,24,19,100,75,51,...,2,12,7,NaN,0.00,0,NaN,178,6,NaN
8,2013-1-9,45,36,28,39,32,25,89,76,65,...,5,18,11,25.0,0.03,3,Rain,211,7,10101
9,2013-1-10,41,34,30,29,27,25,85,69,53,...,8,10,6,NaN,0.00,0,NaN,72,5,NaN